export default {
  INPUT_TEXT: 'INPUT_TEXT',
  INPUT_NUMBER: 'INPUT_NUMBER',
  DROPDOWN: 'DROPDOWN',
  ASYNCDROPDOWN: 'ASYNCDROPDOWN',
  PASSWORD: 'PASSWORD',
  CALENDAR: 'CALENDAR',
  INPUT_TEXTAREA: 'INPUT_TEXTAREA',
  INPUT_SWITCH: 'INPUT_SWITCH',
  SELECT_PRODUCT: 'SELECT_PRODUCT',
  SELECT_STATE: 'SELECT_STATE'
};
