export const STATUS_TYPE = {
    CREATING: 1,
    CREATED: 2,
    CREATE_FAIL: -2,
    DELETING: 3,
    DELETED: 4,
    DELETE_FAIL: -4,
    UPDATING: 5,
    UPDATED: 6,
    UPDATE_FAIL: -6,
}

export const LIST_STATUS_TYPE = [
    STATUS_TYPE.CREATING,
    STATUS_TYPE.CREATED,
    STATUS_TYPE.CREATE_FAIL,
    STATUS_TYPE.DELETING,
    STATUS_TYPE.DELETED,
    STATUS_TYPE.DELETE_FAIL,
    STATUS_TYPE.UPDATING,
    STATUS_TYPE.UPDATED,
    STATUS_TYPE.UPDATE_FAIL,
];

export const LIST_STATUS_TYPE_ACTIVE = [
    STATUS_TYPE.CREATED,
    STATUS_TYPE.DELETING,
    STATUS_TYPE.DELETE_FAIL,
    STATUS_TYPE.UPDATING,
    STATUS_TYPE.UPDATED,
    STATUS_TYPE.UPDATE_FAIL,
];

export const PACKAGE_TEXT = {
    '1': 'TRIAL',
    '2': 'PRO',
    '3': 'ADVANCED',
}
